[package]
name = "fcmaes-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Fast, parallel, gradient-free optimization algorithms implemented in pure Rust."
readme = "README.md"
documentation = "https://docs.rs/fcmaes-core"
homepage = "https://github.com/dietmarwo/fcmaes-rust"
keywords = [
    "optimization",
    "black-box",
    "cma-es",
    "evolutionary",
    "multi-objective",
]
categories = [
    "algorithms",
    "mathematics",
]
publish = ["crates-io"]

[lib]
name = "fcmaes_core"

[dependencies]
rand = "0.8"
rand_pcg = "0.3"
rand_distr = "0.4"
rayon = "1"
nalgebra = "0.33"
libm = "0.2"
